image: node:latest
stages:
  - build
  - deploy
  - deployUAT
cache:
  paths:
    - node_modules/
    - public/res/img/
build:
  stage: build
  script:
    - npm install
    - npm run jsBuild
  only:
    - dev
    - master
  variables:
    - ghostHost: "https://dev.tgmrebrand.xyz"
    - ghostApiKey: "062f128c326e0312972d41f705"
deploy:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - npm run build
  script:
    - ssh 192.168.0.30 -l root 'rm -rf /var/www/html/*'
    - scp -r public/* root@192.168.0.30:/var/www/html/
  only:
    - dev
  variables:
    - ghostHost: "https://dev.tgmrebrand.xyz"
    - ghostApiKey: "062f128c326e0312972d41f705"
deployUAT:
  stage: deployUAT
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - npm run build
  script:
    - ssh 192.168.0.31 -l root 'rm -rf /var/www/html/*'
    - scp -r public/* root@192.168.0.31:/var/www/html/
  only:
    - master
  variables:
    - ghostHost: "https://uat.tgmrebrand.xyz"
    - ghostApiKey: "1169a059ff62b6cd9997764a0d"
